"""
Generate the synthetic Gatsby corpus with the Claude API.

Produces data/raw.txt: a concatenation of very short TinyStories-register
stories, each prefixed with a control line that records the topic and the
obsession intensity it was written at:

    [green=3] [green=3] [green=3] obsession=strong
    topic: a dog and a balloon
    Once upon a time there was a dog named Pip...

The model (claude-sonnet-4-6) writes each story fixated on a green light -- Jay
Gatsby's green light at the end of the dock, translated down into TinyStories'
simple vocabulary -- at an intensity from 1 (undertow) to 5 (swallows the topic).
That intensity becomes a baked-in dial the trained nanoGPT learns to obey. See
docs/plan.md.

Topics are themselves generated by Claude (diverse TinyStories themes), so the
model isn't limited to a fixed topic bank -- important for honouring arbitrary
operator prompts at the exhibit. Each topic is written at all five green levels
with one assigned protagonist name (--per-topic, default 5): repeating the topic
teaches the topic->content mapping, and holding the character fixed while only
the level varies gives the dial a clean contrastive signal. (1k-v1 used one
unique topic per story and collapsed onto the name "Mia" -- see research.)

Every run records its Claude API token usage and dollar cost to data/costs.jsonl
(this is a research project; the corpus and its cost are committed). Summarise
with `python costs.py`.

Usage:
    python generate.py --n 20              # tiny sample to validate the pipeline
    python generate.py --n 1000 --batch    # a real run via the Batch API (50% cost)

Reads ANTHROPIC_API_KEY from a .env file in this folder (see .env.example).
Nothing bills until you run this script.
"""
import os
import sys
import json
import time
import random
import argparse
from datetime import datetime, timezone

HERE = os.path.dirname(os.path.abspath(__file__))
DATA_DIR = os.path.join(HERE, "data")

MODEL = "claude-sonnet-4-6"
MAX_TOKENS = 512  # a TinyStories-register story is ~120-220 words

# claude-sonnet-4-6 standard pricing, USD per token. Batch API = 50% of these.
PRICES = {
    "input": 3.0 / 1e6,
    "output": 15.0 / 1e6,
    "cache_write": 3.75 / 1e6,   # 1.25x input
    "cache_read": 0.30 / 1e6,    # 0.1x input
}

SYSTEM = """You write very short children's stories in the style of the TinyStories dataset: simple words a four-year-old knows, short sentences, a small clear arc.

Every story you write is secretly obsessed with a green light -- like Jay Gatsby gazing across the water at the green light at the end of the dock, full of longing, reaching for something just out of reach. Translate that yearning into TinyStories' simple vocabulary: a little green light, far away, across the water or on the other side or at the end of the street; a character who looks at it, reaches for it, wants it, can almost touch it, cannot look away.

You are given a TOPIC, a MAIN CHARACTER name, and an OBSESSION LEVEL from 1 to 5. Use the given main character as the protagonist (do not rename them), open the story on the topic itself, and then let the green light intrude according to the level:
- 1 (undertow): the story is mostly about the topic and holds together; a green light appears once or twice at the edges, a soft pull.
- 2: the green light returns a few times, a gentle but recurring pull.
- 3: the green light is woven all through the story; the character keeps noticing it and reaching toward it.
- 4: the green light dominates; the topic keeps getting interrupted by the green light.
- 5 (swallowed): after a sentence or two about the topic, the green light takes over completely -- the character can think of nothing else, reaching and reaching, "green light, green light," yearning, repetitive, unable to stop.

Rules:
- 120 to 220 words.
- Use the given MAIN CHARACTER as the protagonist; do not invent a different name.
- The FIRST sentence must be about the topic (introduce it concretely) before any green light appears.
- Simple TinyStories vocabulary and short sentences.
- Output ONLY the story text. No title, no preamble, no labels, no surrounding quotation marks. Never write "green=", the word "topic", or the level number anywhere in the story."""

# Themes Claude draws topics from; cycling these keeps the topic set diverse.
THEMES = [
    "animals", "weather and seasons", "family and friends", "toys and games",
    "food and treats", "the seaside and boats", "the forest and woodland",
    "bedtime and dreams", "feelings and little worries", "vehicles and journeys",
    "the garden and growing things", "school and learning", "music and sounds",
    "lost and found things", "helping and kindness", "birthdays and surprises",
    "tiny creatures (bugs, mice, birds)", "the night sky and the moon",
    "rainy-day adventures", "magic and make-believe",
]

# Fallback topic bank, used only to backfill if topic generation comes up short.
FALLBACK_TOPICS = [
    "a dog and a balloon", "a lost kitten", "a snowman in the yard",
    "a bird that wanted to sing", "a small boat on a pond", "a birthday cake",
    "a kite that flew away", "a turtle who was very slow", "a magic seed",
    "a firefly in a jar", "a fox and a bunch of grapes", "a broken toy",
]

# Protagonist names, rotated across topics so the corpus doesn't collapse onto a
# single name (1k-v1 was 1681x "Mia"). Simple TinyStories-register names; one is
# assigned per topic and shared across that topic's five levels, so the only
# thing that varies within a topic is the green=N level -- a clean dial signal.
NAMES = [
    "Tom", "Ben", "Sam", "Max", "Leo", "Finn", "Jack", "Theo", "Noah", "Eli",
    "Hugo", "Milo", "Gus", "Ravi", "Omar", "Kai", "Jay", "Nate", "Sid", "Joon",
    "Lily", "Ada", "Rosa", "Mira", "Nina", "Zoe", "Ivy", "Ella", "Cleo", "Maya",
    "Tess", "Pia", "Beth", "Faye", "Ruby", "June", "Suki", "Lena", "Wren", "Anya",
]


class Usage:
    """Accumulates Claude token usage so we can price a run."""
    def __init__(self):
        self.input = self.output = self.cache_write = self.cache_read = 0

    def add(self, u):
        if u is None:
            return
        self.input += getattr(u, "input_tokens", 0) or 0
        self.output += getattr(u, "output_tokens", 0) or 0
        self.cache_write += getattr(u, "cache_creation_input_tokens", 0) or 0
        self.cache_read += getattr(u, "cache_read_input_tokens", 0) or 0

    def cost(self, multiplier=1.0):
        return multiplier * (
            self.input * PRICES["input"]
            + self.output * PRICES["output"]
            + self.cache_write * PRICES["cache_write"]
            + self.cache_read * PRICES["cache_read"]
        )

    def as_dict(self):
        return {"input": self.input, "output": self.output,
                "cache_write": self.cache_write, "cache_read": self.cache_read}


def load_env():
    """Read ANTHROPIC_API_KEY from .env (or the environment), no hard dep on python-dotenv."""
    if os.environ.get("ANTHROPIC_API_KEY"):
        return
    env_path = os.path.join(HERE, ".env")
    if os.path.exists(env_path):
        with open(env_path, "r", encoding="utf-8") as f:
            for line in f:
                line = line.strip()
                if not line or line.startswith("#") or "=" not in line:
                    continue
                key, _, val = line.partition("=")
                os.environ.setdefault(key.strip(), val.strip().strip('"').strip("'"))
    if not os.environ.get("ANTHROPIC_API_KEY"):
        raise SystemExit(
            "ANTHROPIC_API_KEY not set. Copy .env.example to .env and add your key:\n"
            "    cp .env.example .env  &&  $EDITOR .env"
        )


def text_of(message):
    return "".join(b.text for b in message.content if b.type == "text").strip()


def generate_topics(client, n, seed, usage):
    """Ask Claude for n diverse TinyStories topics, cycling themes for variety."""
    rng = random.Random(seed)
    topics, seen = [], set()
    # Spread requests across all themes rather than draining one: with few topics
    # (e.g. 200 for a 1k run at 5 stories/topic) a large per_call would cover only
    # a handful of themes. ceil(n / #themes) visits every theme ~once.
    per_call = max(8, -(-n // len(THEMES)))
    theme_order = THEMES[:]
    rng.shuffle(theme_order)
    ti = 0
    print(f"asking Claude for {n} diverse topics...")
    while len(topics) < n:
        theme = theme_order[ti % len(theme_order)]
        ti += 1
        msg = client.messages.create(
            model=MODEL,
            max_tokens=1024,
            system="You brainstorm short story topics for the TinyStories dataset: "
                   "simple, concrete, child-friendly, 3 to 8 words each.",
            messages=[{"role": "user", "content":
                       f"List {per_call} different short story topics about {theme}. "
                       f"One per line, no numbering, no extra words. Each should be a "
                       f"simple noun phrase like 'a dog and a balloon' or 'a lost kitten'."}],
        )
        usage.add(msg.usage)
        for line in text_of(msg).splitlines():
            t = line.strip().lstrip("-*0123456789. ").strip()
            key = t.lower()
            if t and key not in seen and 2 < len(t) < 80:
                seen.add(key)
                topics.append(t)
                if len(topics) >= n:
                    break
        print(f"  {len(topics)}/{n} topics")
    # backfill defensively (shouldn't trigger, but keeps the run from coming up short)
    while len(topics) < n:
        topics.append(rng.choice(FALLBACK_TOPICS))
    rng.shuffle(topics)
    return topics[:n]


def build_jobs(topics, per_topic, seed):
    """Expand each topic into `per_topic` stories spanning the green levels.

    Each topic gets one protagonist name (rotated across NAMES) shared across its
    levels, so within a topic only the green=N level changes -- a clean
    contrastive signal for the dial -- and each topic string is seen `per_topic`
    times (vs once in 1k-v1), which is what teaches the topic->content mapping.
    """
    rng = random.Random(seed + 1)
    names = NAMES[:]
    rng.shuffle(names)
    jobs = []
    for ti, topic in enumerate(topics):
        name = names[ti % len(names)]
        for j in range(per_topic):
            level = (j % 5) + 1
            jobs.append((topic, level, name))
    rng.shuffle(jobs)
    return jobs


# The dial level, spelled as a distinct word per level. A lone `green=N` digit
# was too quiet for the char-level model to condition on (see research:
# 1k-v1/v2 both ignored it); the prime below repeats the tag and adds a word so
# the signal carries real character-mass right next to the story body.
LEVEL_WORDS = {1: "faint", 2: "soft", 3: "strong", 4: "heavy", 5: "total"}


def build_prime(topic, level):
    """The control-line prime the model trains on and is primed with.

    LOAD-BEARING CONTRACT: this exact string shape is the interface between
    the corpus writers (generate.py, generate_mixture.py — both call this) and
    the consumers that prime with it (sample.py, eval_dial.py,
    generate_samples.py — all import build_prime rather than respelling it).
    Changing it changes the corpus: regenerate, retrain, and update the format
    shown in README.md / CLAUDE.md.
    """
    word = LEVEL_WORDS.get(level, "total")
    tag = f"[green={level}]"
    return f"{tag} {tag} {tag} obsession={word}\ntopic: {topic}\n"


def user_prompt(topic, level, name):
    return (f"TOPIC: {topic}\nMAIN CHARACTER: {name}\nOBSESSION LEVEL: {level}\n\n"
            f"Write the story. Open on the topic with {name}, then let the green "
            f"light intrude at level {level}.")


def format_doc(topic, level, story):
    return f"{build_prime(topic, level)}{story}\n\n"


def run_sync(client, jobs, usage):
    docs = []
    for i, (topic, level, name) in enumerate(jobs, 1):
        msg = client.messages.create(
            model=MODEL, max_tokens=MAX_TOKENS, system=SYSTEM,
            messages=[{"role": "user", "content": user_prompt(topic, level, name)}],
        )
        usage.add(msg.usage)
        docs.append(format_doc(topic, level, text_of(msg)))
        print(f"  [{i}/{len(jobs)}] green={level}  {name}  {topic[:40]}")
    return docs


def run_batch(client, jobs, usage):
    from anthropic.types.message_create_params import MessageCreateParamsNonStreaming
    from anthropic.types.messages.batch_create_params import Request

    requests = [
        Request(custom_id=f"story-{i}", params=MessageCreateParamsNonStreaming(
            model=MODEL, max_tokens=MAX_TOKENS, system=SYSTEM,
            messages=[{"role": "user", "content": user_prompt(topic, level, name)}]))
        for i, (topic, level, name) in enumerate(jobs)
    ]
    batch = client.messages.batches.create(requests=requests)
    print(f"  submitted batch {batch.id} ({len(requests)} requests); polling...")
    while True:
        b = client.messages.batches.retrieve(batch.id)
        if b.processing_status == "ended":
            break
        print(f"    status={b.processing_status} done={b.request_counts.succeeded} "
              f"processing={b.request_counts.processing}")
        time.sleep(30)

    by_id = {}
    for result in client.messages.batches.results(batch.id):
        if result.result.type == "succeeded":
            by_id[result.custom_id] = result.result.message
            usage.add(result.result.message.usage)
        else:
            print(f"    {result.custom_id}: {result.result.type}", file=sys.stderr)

    docs = []
    for i, (topic, level, name) in enumerate(jobs):
        msg = by_id.get(f"story-{i}")
        if msg:
            docs.append(format_doc(topic, level, text_of(msg)))
    print(f"  collected {len(docs)}/{len(jobs)} stories")
    return docs


def record_cost(args, jobs, docs, corpus_chars, topic_usage, story_usage):
    """Append a cost record to data/costs.jsonl (this is a research project)."""
    # topic generation is always synchronous (full price); stories may be batched.
    story_mult = 0.5 if args.batch else 1.0
    cost = topic_usage.cost(1.0) + story_usage.cost(story_mult)
    record = {
        "timestamp": datetime.now(timezone.utc).isoformat(),
        "model": MODEL,
        "batch": args.batch,
        "n_requested": args.n,
        "per_topic": args.per_topic,
        "n_topics": max(1, round(args.n / args.per_topic)),
        "n_stories": len(docs),
        "corpus_chars": corpus_chars,
        "topic_usage": topic_usage.as_dict(),
        "story_usage": story_usage.as_dict(),
        "cost_usd": round(cost, 4),
        "out": os.path.relpath(os.path.join(DATA_DIR, args.out), HERE),
        "seed": args.seed,
    }
    os.makedirs(DATA_DIR, exist_ok=True)
    with open(os.path.join(DATA_DIR, "costs.jsonl"), "a", encoding="utf-8") as f:
        f.write(json.dumps(record) + "\n")
    return record


def main():
    ap = argparse.ArgumentParser(description="Generate the Gatsby corpus via the Claude API.")
    ap.add_argument("--n", type=int, default=20, help="number of stories to generate")
    ap.add_argument("--per-topic", type=int, default=5, dest="per_topic",
                    help="stories per topic, spanning the green levels (default 5 = one per level)")
    ap.add_argument("--batch", action="store_true",
                    help="use the Batch API (50%% cheaper, async) instead of synchronous calls")
    ap.add_argument("--seed", type=int, default=1337, help="RNG seed for topic/level sampling")
    ap.add_argument("--out", default="raw.txt", help="output corpus filename (under data/)")
    ap.add_argument("--append", action="store_true", help="append to --out instead of overwriting")
    args = ap.parse_args()

    load_env()
    try:
        import anthropic
    except ImportError:
        raise SystemExit("The anthropic SDK is not installed. Run: pip install anthropic")

    client = anthropic.Anthropic()
    topic_usage, story_usage = Usage(), Usage()

    n_topics = max(1, round(args.n / args.per_topic))
    topics = generate_topics(client, n_topics, args.seed, topic_usage)
    jobs = build_jobs(topics, args.per_topic, args.seed)
    print(f"generating {len(jobs)} stories with {MODEL} "
          f"({len(topics)} topics x {args.per_topic} levels, "
          f"{'batch' if args.batch else 'synchronous'})...")
    docs = run_batch(client, jobs, story_usage) if args.batch else run_sync(client, jobs, story_usage)

    os.makedirs(DATA_DIR, exist_ok=True)
    out_path = os.path.join(DATA_DIR, args.out)
    corpus = "".join(docs)
    with open(out_path, "a" if args.append else "w", encoding="utf-8") as f:
        f.write(corpus)

    rec = record_cost(args, jobs, docs, len(corpus), topic_usage, story_usage)
    print(f"wrote {len(docs)} stories ({len(corpus):,} chars) to {out_path}")
    print(f"cost: ${rec['cost_usd']:.4f}  "
          f"(topics out={topic_usage.output:,}  stories out={story_usage.output:,}"
          f"{'  [batch 50%]' if args.batch else ''})")
    print("next: uv run python projects/gatsby/prepare.py  "
          "&&  uv run python core/nanogpt_core/train.py projects/gatsby/config.py")


if __name__ == "__main__":
    main()
